# -*- coding: utf-8 -*-
"""Greeting Service.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1cPYtKEy5cPpLa7N0tR8g0US12U9CVDew
# GREETING DASHBOARD
"""

import os

class Greetings:
    def __init__(self):
        self.greetings_storage = {}
        self.load_config()

    def load_config(self):
        self.greetings_storage = {
            lang: greet for lang, greet in os.environ.items() if lang.startswith("GREET_")
        }
        print("GREETING DASHBOARD!")
        print("Greetings Storage: ", self.greetings_storage)

    def user_info(self, lang, user):
        self.language = lang
        self.user_name = user
        self.greet()

    def greet(self):
        if self.language in self.greetings_storage:
            print(self.greetings_storage[self.language], self.user_name)
        else:
            print("Sorry, greeting not available in", self.language)

    def store(self, greets):
        self.greetings_storage = greets
        print(self.greetings_storage)

greetObj = Greetings()

"""# ADMIN DASHBOARD"""

# ADMIN

# print("Enter the Languge")
# languge = input()

# print("Enter the Greeting")
# greet = input()

# greetObj.store(languge , greet)

greetingsStorage = {
    "URDU": "Assalam o' Alaikum",
    "ENGLISH" : "Welcome",
    "JAPANESE" : "Konichiwa"
}

greetObj.store(greetingsStorage)

"""# USER DASHBOARD"""

# USER
print("Enter your languge")
languge = input()

print("Enter your User Name")
user = input()

greetObj.user_info(languge , user)
