# -*- coding: utf-8 -*-
"""UnitTest.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/12Fc2MammlmXUFILvqlTpUyBoTWxcND7x
# **TESTING**
"""

import unittest

class TestGreetings(unittest.TestCase):
    def setUp(self):
        self.greetObj = Greetings()
        
    def test_user_info(self):
        self.greetObj.user_info('English', 'John')
        self.assertEqual(self.greetObj.language, 'English')
        self.assertEqual(self.greetObj.user_name, 'John')
        
    def test_greet(self):
        self.greetObj.store({'English': 'Hello', 'Spanish': 'Hola'})
        self.greetObj.user_info('English', 'John')
        self.assertEqual(self.greetObj.greetings_storage['English'], 'Hello')
        
    def test_store(self):
        self.greetObj.store({'English': 'Hello', 'Spanish': 'Hola'})
        self.assertEqual(self.greetObj.greetings_storage, {'English': 'Hello', 'Spanish': 'Hola'})

# if __name__ == '__main__':
#   unittest.main()

#if __name__ == '__main__':
#    unittest.main(argv=['first-arg-is-ignored'], exit=False)
